INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES
(1, 'PS3', 'PlayStation 3');
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES
(2, 'PS3 Slim', 'PlayStation 3 Slim');
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES
(3, 'XBOX One', 'XBOX One');
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES
(4, 'PS4 Pro', 'PlayStation 4 Pro 4k');
INSERT INTO IMAGE (ID, TYPE, PRODUCT_ID) VALUES
(1, 'PNG', 1);
INSERT INTO IMAGE (ID, TYPE, PRODUCT_ID) VALUES
(2, 'JPEG', 2);
INSERT INTO IMAGE (ID, TYPE, PRODUCT_ID) VALUES
(3, 'JPEG', 3);